### ISSUE TITLE
The peyotl install TL;DR doesn't work

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentreeoflife.github.io#2]
http://opentreeoflife.github.io/peyotl/installation/

Maybe it needs a 'sudo'? The venv instructions work fine.

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/cf/f43r04ls6pxbxm76k8s6n5x80000gn/T/pip_build_jar/anyjson/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/cf/f43r04ls6pxbxm76k8s6n5x80000gn/T/pip-YuN7ht-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/cf/f43r04ls6pxbxm76k8s6n5x80000gn/T/pip_build_jar/anyjson
Storing debug log for failure in /Users/jar/Library/Logs/pip.log

**Comment by mtholder** [comment]
fixed.
