### ISSUE TITLE
Validation example missing correct PYTHONPATH or something

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/opentreeoflife.github.io#3]
http://opentreeoflife.github.io/peyotl/nexson-validation/

After installing peyotl as instructred, I tried what this page says:

```
./scripts/nexson/validate_ot_nexson.py "../oti/ot_232?output_nexml2json=1.2.1"
```

and got

```
ImportError: No module named peyotl.nexson_syntax
```

**Comment by jar398** [comment]
Hmm... need to read the configuration section

**Comment by jar398** [comment]
No, config section doesn't explain it.  Looks like the following fixes the problem (so should be either documented or made unnecessary):
    export PYTHONPATH=.
where . would be the root of the peyotl repo clone.    (how many mixed metaphors can we get into one sentence?)

**Comment by mtholder** [comment]
If adding the dir to your `PYTHONPATH` did the trick, then either:
  1. you did not install `peyotl`, or
  2. you installed it using `virtualenv` but forgot to `source` the virtualenv's `.../bin/activate` script in the shell session from which you ran the `validate_ot_nexson.py`

Or something like that.

**Comment by jar398** [comment]
This is a documentation bug report, not a question as to how to solve the problem.

**Comment by mtholder** [comment]
Sorry - I can't replicate this when I follow the installation instructions.
